### ISSUE TITLE
Opção de copiar e colar código

### ISSUE THREAD

**Issue by andrealvesaraujo** [sucodelarangela/codeshare#4]
Uma sugestão de melhoria.

Além do botão de salvar foto do código, poderia deixar um ícone no card para salvar o código que botou ai.

Assim vai ajudar no compartilhamento de códigos.

**Comment by sucodelarangela** [comment]
No caso, copiar o conteúdo de texto do código, certo? Boa!

**Comment by andrealvesaraujo** [comment]
> No caso, copiar o conteúdo de texto do código, certo? Boa!

Sim

**Comment by sucodelarangela** [comment]
Obrigada pela issue. Sugestão implementada e em funcionamento!
